import { route } from "@/lib/api/handler";
import * as controller from "@/controllers/checkout.controller";

/**
 * The commercial invoice PDF for a filed shipment, generated by Shiprocket on
 * demand. 404s until a shipment exists for the order.
 */
export const GET = route<{ orderNumber: string }>(({ request, params }) =>
  controller.getShipmentInvoice(request, params),
);
