import { NextResponse } from "next/server";
import { route } from "@/lib/api/handler";
import { parseParams } from "@/lib/api/validate";
import { orderNumberParam } from "@/validators/checkout";
import * as orderService from "@/services/order.service";
import * as shippingService from "@/services/shipping.service";
import { requireStaff } from "@/lib/auth/session";

/**
 * The commercial invoice PDF for a filed shipment, generated by Shiprocket on
 * demand. 404s until a shipment exists for the order.
 */
export const GET = route<{ orderNumber: string }>(async ({ request, params }) => {
  await requireStaff(request, "shipment:read");
  const { orderNumber } = parseParams(params, orderNumberParam);

  const order = await orderService.getOrderByNumberForStaff(orderNumber);
  const invoiceUrl = await shippingService.getInvoiceUrl(String(order._id));

  return NextResponse.json(
    { success: true, status: 200, message: "Invoice fetched successfully", data: { invoiceUrl } },
    { status: 200 },
  );
});
